"""Generate exact status lists from actual files and source-matched execution evidence."""
import json
import nbformat
from academy_tools import ROOT, inventory, source_hash

def main():
    records = inventory()
    path = ROOT/'reports/execution_results.json'
    execution = json.loads(path.read_text())['notebooks'] if path.exists() else {}
    review_path = ROOT/'reports/content_review.json'
    reviews = json.loads(review_path.read_text()) if review_path.exists() else {}
    groups = {name:[] for name in ['Executed and verified','Executed; review pending','Generated draft; unexecuted and incomplete','Written but untested','In development','Blocked or optional','Planned']}
    for record in records:
        notebook_path = ROOT/record['path']
        if notebook_path.exists():
            notebook = nbformat.read(notebook_path, as_version=4)
            digest = source_hash(notebook)
            evidence = execution.get(record['id'], {})
            passed = evidence.get('status') == 'passed' and evidence.get('source_sha256') == digest
            reviewed = reviews.get(record['id'], {}).get('source_sha256') == digest
            if notebook.metadata.get('academy', {}).get('authoring_status') == 'draft': status = 'Generated draft; unexecuted and incomplete'
            elif passed and reviewed: status = 'Executed and verified'
            elif passed: status = 'Executed; review pending'
            elif evidence.get('status') == 'failed' and evidence.get('source_sha256') == digest: status = 'In development'
            else: status = 'Written but untested'
        elif (ROOT/'lesson_sources'/f'{record["id"]}.lesson').exists(): status = 'In development'
        else: status = 'Blocked or optional' if record['optional'] else 'Planned'
        record['status'] = status
        groups[status].append(record)
    created = sum((ROOT/r['path']).exists() for r in records)
    next_batch = [r for r in records if r['module'] == '02' and r['status'] == 'Generated draft; unexecuted and incomplete'][:3]
    if not next_batch:
        next_batch = [r for r in records if r['module'] == '01' and not (ROOT/r['path']).exists()][:3]
    if not next_batch:
        next_batch = [r for r in records if r['module'] == '02' and not (ROOT/r['path']).exists()][:3]
    next_description = ', '.join(f'{r["id"]} {r["title"]}' for r in next_batch) or 'the next unfinished foundation lessons in prerequisite order'
    rows = ['# Academy progress — authoritative status', '',
        f'Inventory: **{len(records)}** notebooks. Created: **{created}**. Executed and reviewed at the current source hash: **{len(groups["Executed and verified"])}**. Unwritten: **{len(records)-created}**.', '',
        f'Generated incomplete drafts: **{len(groups["Generated draft; unexecuted and incomplete"])}**. The user requested generation and static checks only for this expansion; no new notebook executions were performed. All files existing does not mean the complete educational program is finished.', '',
        'A lesson is verified only when its current source matches a passing fresh-kernel execution and a recorded content review. Changed sources invalidate earlier evidence. Optional means planned with extra dependencies; it does not mean completed.', '',
        '## Immediate next actions', '',
        '1. Read the latest reports and resolve any failed or stale notebooks below.',
        f'2. Expand and review the next foundation drafts: {next_description}. Preserve the generation-only policy unless the user changes it.',
        '3. Prioritize the classical algorithm sequence after those prerequisites: regression/gradient descent, logistic regression, KNN, Naive Bayes, trees/forests, SVM, boosting, evaluation/CV/tuning, K-Means, PCA, DBSCAN.',
        '4. Expand the reference guides alongside their lessons; the current comparison and interview guides are foundation/core editions, not complete advanced textbooks.', '',
        '## Scope and limitations', '',
        '- All 24 modules retain the complete inventory. Generated drafts contain topic briefs and code starting points; their complete educational treatment remains pending.',
        '- The environment smoke notebook is an infrastructure check and is excluded from the curriculum count.',
        '- No optional packages, large model downloads, cloud accounts, or external deployments are required by the current lessons.',
        '- Study plans select a core route; completing every planned extension takes longer than 12 or 36 weeks.',
        '- Counts and links are generated by scripts/update_progress.py; do not hand-mark planned work as complete.', '',
        '## Evidence', '',
        '[Execution results](reports/execution_results.json) · [Structural checks](reports/structural_checks.json) · [Content review](reports/CONTENT_REVIEW.md) · [Syllabus](SYLLABUS.md)', '',
        '## Modules', '', '| Module | Created | Total planned | Verified | Incomplete drafts |', '|---|---:|---:|---:|---:|']
    for module in sorted({r['module'] for r in records}):
        entries = [r for r in records if r['module']==module]
        rows.append(f'| {module} | {sum((ROOT/r["path"]).exists() for r in entries)} | {len(entries)} | {sum(r["status"]=="Executed and verified" for r in entries)} | {sum(r["status"]=="Generated draft; unexecuted and incomplete" for r in entries)} |')
    for status, entries in groups.items():
        rows += ['', f'## {status} ({len(entries)})', '']
        if not entries: rows += ['None.']
        for r in entries:
            target = r['path'] if (ROOT/r['path']).exists() else str(__import__('pathlib').Path(r['path']).parent).replace('\\','/') + '/README.md#' + r['id']
            rows.append(f'- {r["id"]} [{r["title"]}]({target})')
    rows += ['', '## Exact continuation prompt', '',
        f'> Continue improving complete-machine-learning-academy in this workspace. Read AGENTS.md, PROGRESS.md, and reports/GENERATION_ONLY_REPORT.md. Preserve all 427 notebook files and existing reviewed lessons. Expand {next_description} from drafts into full 21-section lessons with manual mathematics, scratch/library implementations, meaningful plots, six worked exercises, and answered questions. Check syntax, static logic, prerequisites and links without executing notebooks unless I explicitly change that policy. Keep unexecuted and incomplete status honest, update progress, commit and push each coherent batch without force. Do not install optional packages or deploy services.', '']
    (ROOT/'PROGRESS.md').write_text('\n'.join(rows), encoding='utf-8')
    print(f'Progress updated: {created} created, {len(groups["Executed and verified"])} verified, {len(records)-created} unwritten.')

if __name__ == '__main__': main()
