"""Generate exact status lists from actual files and source-matched execution evidence."""
import json
import nbformat
from academy_tools import ROOT, inventory, source_hash

def main():
    records = inventory()
    path = ROOT/'reports/execution_results.json'
    execution = json.loads(path.read_text())['notebooks'] if path.exists() else {}
    review_path = ROOT/'reports/content_review.json'
    reviews = json.loads(review_path.read_text()) if review_path.exists() else {}
    groups = {name:[] for name in ['Executed and verified','Executed; review pending','Written but untested','In development','Blocked or optional','Planned']}
    for record in records:
        notebook_path = ROOT/record['path']
        if notebook_path.exists():
            digest = source_hash(nbformat.read(notebook_path, as_version=4))
            evidence = execution.get(record['id'], {})
            passed = evidence.get('status') == 'passed' and evidence.get('source_sha256') == digest
            reviewed = reviews.get(record['id'], {}).get('source_sha256') == digest
            if passed and reviewed: status = 'Executed and verified'
            elif passed: status = 'Executed; review pending'
            elif evidence.get('status') == 'failed' and evidence.get('source_sha256') == digest: status = 'In development'
            else: status = 'Written but untested'
        elif (ROOT/'lesson_sources'/f'{record["id"]}.lesson').exists(): status = 'In development'
        else: status = 'Blocked or optional' if record['optional'] else 'Planned'
        record['status'] = status
        groups[status].append(record)
    created = sum((ROOT/r['path']).exists() for r in records)
    next_batch = [r for r in records if r['module'] == '01' and not (ROOT/r['path']).exists()][:3]
    next_description = ', '.join(f'{r["id"]} {r["title"]}' for r in next_batch) or 'the next unfinished foundation lessons in prerequisite order'
    rows = ['# Academy progress — authoritative status', '',
        f'Inventory: **{len(records)}** notebooks. Created: **{created}**. Executed and reviewed at the current source hash: **{len(groups["Executed and verified"])}**. Unwritten: **{len(records)-created}**.', '',
        'A lesson is verified only when its current source matches a passing fresh-kernel execution and a recorded content review. Changed sources invalidate earlier evidence. Optional means planned with extra dependencies; it does not mean completed.', '',
        '## Immediate next actions', '',
        '1. Read the latest reports and resolve any failed or stale notebooks below.',
        f'2. Implement the next foundation batch: {next_description}. Then fill mathematics and preprocessing prerequisites.',
        '3. Prioritize the classical algorithm sequence after those prerequisites: regression/gradient descent, logistic regression, KNN, Naive Bayes, trees/forests, SVM, boosting, evaluation/CV/tuning, K-Means, PCA, DBSCAN.',
        '4. Expand the reference guides alongside their lessons; the current comparison and interview guides are foundation/core editions, not complete advanced textbooks.', '',
        '## Scope and limitations', '',
        '- All 24 modules have a complete planned inventory and module specifications. Only files listed as created below contain lessons.',
        '- The environment smoke notebook is an infrastructure check and is excluded from the curriculum count.',
        '- No optional packages, large model downloads, cloud accounts, or external deployments are required by the current lessons.',
        '- Study plans select a core route; completing every planned extension takes longer than 12 or 36 weeks.',
        '- Counts and links are generated by scripts/update_progress.py; do not hand-mark planned work as complete.', '',
        '## Evidence', '',
        '[Execution results](reports/execution_results.json) · [Structural checks](reports/structural_checks.json) · [Content review](reports/CONTENT_REVIEW.md) · [Syllabus](SYLLABUS.md)', '',
        '## Modules', '', '| Module | Created | Total planned | Verified |', '|---|---:|---:|---:|']
    for module in sorted({r['module'] for r in records}):
        entries = [r for r in records if r['module']==module]
        rows.append(f'| {module} | {sum((ROOT/r["path"]).exists() for r in entries)} | {len(entries)} | {sum(r["status"]=="Executed and verified" for r in entries)} |')
    for status, entries in groups.items():
        rows += ['', f'## {status} ({len(entries)})', '']
        if not entries: rows += ['None.']
        for r in entries:
            target = r['path'] if (ROOT/r['path']).exists() else str(__import__('pathlib').Path(r['path']).parent).replace('\\','/') + '/README.md#' + r['id']
            rows.append(f'- {r["id"]} [{r["title"]}]({target})')
    rows += ['', '## Exact continuation prompt', '',
        f'> Continue building complete-machine-learning-academy in this workspace. Read AGENTS.md, PROGRESS.md, and reports first. Preserve the 427-notebook inventory. Implement {next_description} with lesson-specific explanations, manual examples, runnable code, six exercises and worked solutions, and answered knowledge/interview questions. Use the existing .venv, execute each new notebook in a fresh kernel, inspect its outputs, run structural/link checks and infrastructure tests, record content reviews tied to source and declared dependency hashes, and regenerate PROGRESS.md. Do not install optional packages unless the selected lessons require them. Report exact created and verified counts and the next batch.', '']
    (ROOT/'PROGRESS.md').write_text('\n'.join(rows), encoding='utf-8')
    print(f'Progress updated: {created} created, {len(groups["Executed and verified"])} verified, {len(records)-created} unwritten.')

if __name__ == '__main__': main()
